// src/react/primitives/CheckoutButton.tsx
import { useState, type PropsWithChildren } from "react";
import {
  defaultBillingLabels,
  type BillingLabels,
} from "../../core/i18n.js";

export const CheckoutButton = ({
  productId,
  href,
  disabled = false,
  className = "",
  onCheckout,
  labels = defaultBillingLabels,
  children,
}: PropsWithChildren<{
  productId: string;
  href?: string;
  disabled?: boolean;
  className?: string;
  onCheckout?: (payload: { productId: string }) => Promise<void> | void;
  labels?: BillingLabels;
}>) => {
  const [isLoading, setIsLoading] = useState(false);

  const handleClick = async () => {
    if (disabled || isLoading || !onCheckout) return;
    setIsLoading(true);
    try {
      await onCheckout({ productId });
    } finally {
      setIsLoading(false);
    }
  };

  if (onCheckout) {
    return (
      <button
        type="button"
        className={`button-filled disabled:cursor-not-allowed disabled:opacity-60 ${className}`}
        disabled={disabled}
        onClick={handleClick}
      >
        {children ??
          (isLoading ? labels.checkout.loading : labels.checkout.checkout)}
      </button>
    );
  }

  return (
    <a href={href} className={`button-filled ${className}`}>
      {children ?? labels.checkout.checkout}
    </a>
  );
};

// src/svelte/primitives/CheckoutButton.svelte
<script lang="ts">
  /* global $props, $state */
  import type { Snippet } from "svelte";
  import {
    defaultBillingLabels,
    type BillingLabels,
  } from "../../core/i18n.js";

  interface Props {
    productId: string;
    href?: string;
    disabled?: boolean;
    className?: string;
    onCheckout?: (payload: { productId: string }) => Promise<void> | void;
    labels?: BillingLabels;
    children?: Snippet;
  }

  let {
    productId,
    href = undefined,
    disabled = false,
    className = "",
    onCheckout,
    labels = defaultBillingLabels,
    children,
  }: Props = $props();

  let isLoading = $state(false);

  const handleClick = (event: MouseEvent) => {
    event.preventDefault();
    event.stopPropagation();
    if (disabled || isLoading || !onCheckout) return;
    isLoading = true;
    Promise.resolve(onCheckout({ productId })).finally(() => {
      isLoading = false;
    });
  };
</script>

{#if onCheckout}
  <button
    type="button"
    class={`button-filled disabled:cursor-not-allowed disabled:opacity-60 ${className}`}
    {disabled}
    onclick={handleClick}
  >
    {#if children}
      {@render children()}
    {:else}
      {isLoading ? labels.checkout.loading : labels.checkout.checkout}
    {/if}
  </button>
{:else}
  <a
    href={href}
    class={`button-filled ${className}`}
  >
    {#if children}
      {@render children()}
    {:else}
      {labels.checkout.checkout}
    {/if}
  </a>
{/if}
