// src/react/primitives/OneTimePaymentStatusBadge.tsx
import type { OneTimePaymentStatus } from "../../core/types.js";
import {
  defaultBillingLabels,
  type BillingLabels,
} from "../../core/i18n.js";

export const OneTimePaymentStatusBadge = ({
  status,
  className = "",
  labels = defaultBillingLabels,
}: {
  status: OneTimePaymentStatus;
  className?: string;
  labels?: BillingLabels;
}) => {
  return (
    <span className={className}>{labels.oneTimePaymentStatus[status]}</span>
  );
};

// src/svelte/primitives/OneTimePaymentStatusBadge.svelte
<script lang="ts">
  /* global $props */
  import type { OneTimePaymentStatus } from "../../core/types.js";
  import {
    defaultBillingLabels,
    type BillingLabels,
  } from "../../core/i18n.js";

  interface Props {
    status: OneTimePaymentStatus;
    className?: string;
    labels?: BillingLabels;
  }

  let { status, className = "", labels = defaultBillingLabels }: Props = $props();
</script>

<span class={className}>{labels.oneTimePaymentStatus[status]}</span>
