// src/react/primitives/TrialLimitBanner.tsx
import type { BillingSnapshot } from "../../core/types.js";

export const TrialLimitBanner = ({
  snapshot,
  trialEndsAt,
  className = "",
}: {
  snapshot?: BillingSnapshot | null;
  trialEndsAt?: string | null;
  className?: string;
}) => {
  const trialSubscription = snapshot?.subscriptions.find(
    (subscription) => subscription.status === "trialing",
  );

  if (!trialSubscription) {
    return null;
  }

  const resolvedTrialEnd = trialEndsAt ?? trialSubscription.trialEnd ?? null;

  return (
    <div
      className={`rounded-lg border border-sky-300 bg-sky-50 px-4 py-3 text-sm text-sky-900 dark:border-sky-800 dark:bg-sky-950/40 dark:text-sky-200 ${className}`}
    >
      Trial plan active
      {resolvedTrialEnd
        ? ` until ${new Date(resolvedTrialEnd).toLocaleDateString()}.`
        : ". Upgrade before your trial ends to avoid interruptions."}
    </div>
  );
};

// src/svelte/primitives/TrialLimitBanner.svelte
<script lang="ts">
  import type { BillingSnapshot } from "../../core/types.js";

  interface Props {
    snapshot?: BillingSnapshot | null;
    trialEndsAt?: string | null;
    className?: string;
  }

  let { snapshot, trialEndsAt = null, className = "" }: Props = $props();

  const trialSubscription = $derived(
    snapshot?.subscriptions.find((subscription) => subscription.status === "trialing") ?? null,
  );
  const show = $derived(trialSubscription != null);
  const resolvedTrialEnd = $derived(
    trialEndsAt ?? trialSubscription?.trialEnd ?? null,
  );
</script>

{#if show}
  <div
    class={`rounded-lg border border-sky-300 bg-sky-50 px-4 py-3 text-sm text-sky-900 dark:border-sky-800 dark:bg-sky-950/40 dark:text-sky-200 ${className}`}
  >
    Trial plan active
    {#if resolvedTrialEnd}
      until {new Date(resolvedTrialEnd).toLocaleDateString()}.
    {:else}
      . Upgrade before your trial ends to avoid interruptions.
    {/if}
  </div>
{/if}
