// src/react/widgets/BillingPortal.tsx
import { useMemo, useState, type PropsWithChildren } from "react";
import { useQuery, useConvex } from "convex/react";
import { CustomerPortalButton } from "../primitives/CustomerPortalButton.js";
import {
  requireCreemConvexApi,
  useCreemConvex,
} from "../CreemConvexProvider.js";
import type { BillingPermissions, ConnectedBillingModel } from "./types.js";
import { resolveBillingI18n } from "../../core/i18n.js";

export const BillingPortal = ({
  permissions,
  className = "",
  children,
}: PropsWithChildren<{
  permissions?: BillingPermissions;
  class?: string;
  className?: string;
}>) => {
  const provider = useCreemConvex();
  const resolvedApi = requireCreemConvexApi("BillingPortal", provider);
  const resolvedPermissions = permissions ?? provider?.permissions;
  const i18n = useMemo(
    () => resolveBillingI18n(provider?.i18n),
    [provider?.i18n],
  );
  const canAccess = resolvedPermissions?.canAccessPortal !== false;

  const client = useConvex();

  const billingUiModelRef = resolvedApi.uiModel;
  const portalUrlRef = resolvedApi.customers?.portalUrl;

  const modelRaw = useQuery(billingUiModelRef, {});
  const model = modelRaw as ConnectedBillingModel | undefined;
  const hasCreemCustomer = model?.hasCreemCustomer ?? false;

  const [isLoading, setIsLoading] = useState(false);

  const openPortal = async () => {
    if (!portalUrlRef) return;
    setIsLoading(true);
    try {
      const { url } = await client.action(portalUrlRef, {});
      window.open(url, "_blank", "noopener,noreferrer");
    } finally {
      setIsLoading(false);
    }
  };

  if (!portalUrlRef || !hasCreemCustomer || !canAccess) return null;

  return (
    <CustomerPortalButton
      disabled={isLoading}
      onOpenPortal={openPortal}
      className={className}
      labels={i18n.labels}
    >
      {children ?? i18n.labels.portal.manageBilling}
    </CustomerPortalButton>
  );
};

// src/svelte/widgets/BillingPortal.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { useConvexClient, useQuery } from "@mmailaender/convex-svelte";
  import CustomerPortalButton from "../primitives/CustomerPortalButton.svelte";
  import type { BillingPermissions, ConnectedBillingModel } from "./types.js";
  import type { Snippet } from "svelte";
  import {
    CREEM_CONVEX_CONTEXT_KEY,
    type CreemConvexContextValue,
  } from "../creemConvexContext.js";
  import { resolveBillingI18n } from "../../core/i18n.js";

  interface Props {
    permissions?: BillingPermissions;
    class?: string;
    children?: Snippet;
  }

  let { permissions = undefined, class: className = "", children }: Props = $props();

  const provider = getContext<CreemConvexContextValue | undefined>(
    CREEM_CONVEX_CONTEXT_KEY,
  );
  const resolvedApi = provider?.api;
  if (!resolvedApi) {
    throw new Error(
      "BillingPortal must be rendered inside <CreemConvexProvider>.",
    );
  }
  const resolvedPermissions = $derived(permissions ?? provider?.permissions);
  const i18n = $derived(resolveBillingI18n(provider?.i18n));

  const canAccess = $derived(resolvedPermissions?.canAccessPortal !== false);

  const client = useConvexClient();

  const billingUiModelRef = resolvedApi.uiModel;
  const portalUrlRef = resolvedApi.customers?.portalUrl;

  const billingModelQuery = useQuery(billingUiModelRef, {});
  const model = $derived(billingModelQuery.data as ConnectedBillingModel | undefined);
  const hasCreemCustomer = $derived(model?.hasCreemCustomer ?? false);

  let isLoading = $state(false);

  const openPortal = async () => {
    if (!portalUrlRef) return;
    isLoading = true;
    try {
      const { url } = await client.action(portalUrlRef, {});
      window.open(url, "_blank", "noopener,noreferrer");
    } finally {
      isLoading = false;
    }
  };
</script>

{#if portalUrlRef && hasCreemCustomer && canAccess}
  <CustomerPortalButton
    disabled={isLoading}
    onOpenPortal={openPortal}
    {className}
    labels={i18n.labels}
  >
    {#if children}
      {@render children()}
    {:else}
      {i18n.labels.portal.manageBilling}
    {/if}
  </CustomerPortalButton>
{/if}
