// src/react/widgets/SubscriptionIntervalSelector.tsx
import { useContext } from "react";
import { SegmentGroup } from "../primitives/SegmentGroup.js";
import type { RecurringCycle } from "../../core/types.js";
import { SubscriptionContext } from "./subscriptionContext.js";

const CYCLE_LABELS: Record<string, string> = {
  "every-month": "Monthly",
  "every-three-months": "Quarterly",
  "every-six-months": "Semi-annual",
  "every-year": "Yearly",
};

/**
 * Renders the billing interval selector control.
 *
 * Automatically hides when only one interval is available for the active group.
 * Typically placed inside `Subscription.Root` with `intervalSelector="external"`.
 *
 * @example
 * ```tsx
 * <Subscription.Root intervalSelector="external">
 *   <Subscription.IntervalSelector className="interval-control" />
 * </Subscription.Root>
 * ```
 */
export const SubscriptionIntervalSelector = ({
  cycles,
  value,
  onValueChange,
  className = "",
}: {
  cycles?: RecurringCycle[];
  value?: RecurringCycle;
  onValueChange?: (cycle: RecurringCycle) => void;
  className?: string;
}) => {
  const rootContext = useContext(SubscriptionContext);
  const resolvedCycles = cycles ?? rootContext?.availableCycles ?? [];
  const requestedValue =
    value ?? rootContext?.selectedCycle ?? resolvedCycles[0];
  const resolvedValue =
    requestedValue && resolvedCycles.includes(requestedValue)
      ? requestedValue
      : resolvedCycles[0];
  const handleValueChange = onValueChange ?? rootContext?.setCycle;
  const unstyled = rootContext?.unstyled ?? false;

  if (resolvedCycles.length <= 1 || !resolvedValue || !handleValueChange) {
    return null;
  }

  const items = resolvedCycles.map((cycle) => ({
    value: cycle,
    label: CYCLE_LABELS[cycle] ?? cycle,
  }));

  return (
    <div
      className={
        unstyled
          ? className
          : `creem-base:flex creem-base:justify-center ${className}`
      }
    >
      <SegmentGroup
        items={items}
        value={resolvedValue}
        unstyled={unstyled}
        onValueChange={(v) => handleValueChange(v as RecurringCycle)}
      />
    </div>
  );
};

// src/svelte/widgets/SubscriptionIntervalSelector.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import SegmentGroup from "../primitives/SegmentGroup.svelte";
  import type { RecurringCycle } from "../../core/types.js";
  import {
    SUBSCRIPTION_CONTEXT_KEY,
    type SubscriptionContextValue,
  } from "./subscriptionContext.js";

  const CYCLE_LABELS: Record<string, string> = {
    "every-month": "Monthly",
    "every-three-months": "Quarterly",
    "every-six-months": "Semi-annual",
    "every-year": "Yearly",
  };

  interface Props {
    cycles?: RecurringCycle[];
    value?: RecurringCycle;
    onValueChange?: (cycle: RecurringCycle) => void;
    class?: string;
  }

  let {
    cycles,
    value,
    onValueChange,
    class: className = "",
  }: Props = $props();
  const rootContext = getContext<SubscriptionContextValue | undefined>(
    SUBSCRIPTION_CONTEXT_KEY,
  );
  const resolvedCycles = $derived(cycles ?? rootContext?.availableCycles() ?? []);
  const requestedValue = $derived(
    value ?? rootContext?.getSelectedCycle() ?? resolvedCycles[0],
  );
  const resolvedValue = $derived(
    requestedValue && resolvedCycles.includes(requestedValue)
      ? requestedValue
      : resolvedCycles[0],
  );
  const unstyled = $derived(rootContext?.getUnstyled() ?? false);
  const resolvedClass = $derived(
    unstyled ? className : `creem-base:flex creem-base:justify-center ${className}`,
  );

  const items = $derived(
    resolvedCycles.map((cycle) => ({
      value: cycle,
      label: CYCLE_LABELS[cycle] ?? cycle,
    })),
  );
  const handleValueChange = (next: string) => {
    const cycle = next as RecurringCycle;
    if (onValueChange) {
      onValueChange(cycle);
      return;
    }
    rootContext?.setCycle(cycle);
  };
</script>

{#if resolvedCycles.length > 1 && resolvedValue}
  <div class={resolvedClass}>
    <SegmentGroup
      {items}
      value={resolvedValue}
      {unstyled}
      onValueChange={handleValueChange}
    />
  </div>
{/if}
