// src/svelte/CreemConvexProvider.svelte
<script lang="ts">
  import { setContext, type Snippet } from "svelte";
  import type { PlanCatalog, RecurringCycle } from "../core/types.js";
  import type { BillingI18n } from "../core/i18n.js";
  import {
    CREEM_CONVEX_CONTEXT_KEY,
    type CreemConvexContextValue,
  } from "./creemConvexContext.js";
  import type {
    BillingPermissions,
    CheckoutIntent,
    ConnectedBillingApi,
    PlanChangeIntent,
  } from "./widgets/types.js";

  interface Props {
    api: ConnectedBillingApi;
    catalog?: PlanCatalog;
    defaultCycle?: RecurringCycle;
    permissions?: BillingPermissions;
    onBeforeCheckout?: (intent: CheckoutIntent) => Promise<boolean> | boolean;
    onBeforePlanChange?: (
      intent: PlanChangeIntent,
    ) => Promise<boolean> | boolean;
    onBeforeFreePlanActivation?: (intent: {
      freePlanId: string;
    }) => Promise<boolean> | boolean;
    i18n?: BillingI18n;
    children?: Snippet;
  }

  let {
    api,
    catalog = undefined,
    defaultCycle = undefined,
    permissions = undefined,
    onBeforeCheckout = undefined,
    onBeforePlanChange = undefined,
    onBeforeFreePlanActivation = undefined,
    i18n = undefined,
    children,
  }: Props = $props();

  const contextValue: CreemConvexContextValue = {
    get api() {
      return api;
    },
    get catalog() {
      return catalog;
    },
    get defaultCycle() {
      return defaultCycle;
    },
    get permissions() {
      return permissions;
    },
    get onBeforeCheckout() {
      return onBeforeCheckout;
    },
    get onBeforePlanChange() {
      return onBeforePlanChange;
    },
    get onBeforeFreePlanActivation() {
      return onBeforeFreePlanActivation;
    },
    get i18n() {
      return i18n;
    },
  };

  setContext(CREEM_CONVEX_CONTEXT_KEY, contextValue);
</script>

{@render children?.()}

// src/react/CreemConvexProvider.tsx
/* eslint-disable react-refresh/only-export-components */
import {
  createContext,
  useContext,
  useMemo,
  type PropsWithChildren,
} from "react";
import type { PlanCatalog, RecurringCycle } from "../core/types.js";
import type { BillingI18n } from "../core/i18n.js";
import type {
  BillingPermissions,
  CheckoutIntent,
  ConnectedBillingApi,
  PlanChangeIntent,
} from "./widgets/types.js";

export interface CreemConvexContextValue {
  api: ConnectedBillingApi;
  catalog?: PlanCatalog;
  defaultCycle?: RecurringCycle;
  permissions?: BillingPermissions;
  onBeforeCheckout?: (intent: CheckoutIntent) => Promise<boolean> | boolean;
  onBeforePlanChange?: (intent: PlanChangeIntent) => Promise<boolean> | boolean;
  onBeforeFreePlanActivation?: (intent: {
    freePlanId: string;
  }) => Promise<boolean> | boolean;
  i18n?: BillingI18n;
}

const CreemConvexContext = createContext<CreemConvexContextValue | null>(null);

export const useCreemConvex = () => useContext(CreemConvexContext);

export const requireCreemConvexApi = (
  componentName: string,
  provider: CreemConvexContextValue | null,
) => {
  const resolvedApi = provider?.api;
  if (!resolvedApi) {
    throw new Error(
      `${componentName} must be rendered inside <CreemConvexProvider>.`,
    );
  }
  return resolvedApi;
};

export const CreemConvexProvider = ({
  api,
  catalog,
  defaultCycle,
  permissions,
  onBeforeCheckout,
  onBeforePlanChange,
  onBeforeFreePlanActivation,
  i18n,
  children,
}: PropsWithChildren<CreemConvexContextValue>) => {
  const value = useMemo(
    () => ({
      api,
      catalog,
      defaultCycle,
      permissions,
      onBeforeCheckout,
      onBeforePlanChange,
      onBeforeFreePlanActivation,
      i18n,
    }),
    [
      api,
      catalog,
      defaultCycle,
      permissions,
      onBeforeCheckout,
      onBeforePlanChange,
      onBeforeFreePlanActivation,
      i18n,
    ],
  );

  return (
    <CreemConvexContext.Provider value={value}>
      {children}
    </CreemConvexContext.Provider>
  );
};
