// src/svelte/widgets/BillingHistory.svelte
<script lang="ts">
  import { useConvexClient } from "@mmailaender/convex-svelte";
  import { Pagination } from "@ark-ui/svelte/pagination";
  import type {
    PaginationPageChangeDetails,
    UsePaginationContext,
  } from "@ark-ui/svelte/pagination";
  import { ChevronLeft, ChevronRight } from "@lucide/svelte";
  import type {
    ConnectedBillingApi,
    ConnectedTransaction,
    ConnectedTransactionList,
  } from "./types.js";
  import { formatPrice } from "../primitives/shared.js";

  interface Props {
    api: ConnectedBillingApi;
    pageSize?: number;
    productId?: string;
    orderId?: string;
    class?: string;
  }

  let {
    api,
    pageSize = 10,
    productId = undefined,
    orderId = undefined,
    class: className = "",
  }: Props = $props();

  const client = useConvexClient();
  // svelte-ignore state_referenced_locally
  const searchRef = api.transactions?.search;

  let pageNumber = $state(1);
  let result = $state<ConnectedTransactionList | null>(null);
  let isLoading = $state(false);
  let error = $state<string | null>(null);

  const normalizeTimestamp = (timestamp: number | undefined): number | null => {
    if (!timestamp) return null;
    return timestamp < 1_000_000_000_000 ? timestamp * 1000 : timestamp;
  };

  const formatDate = (timestamp: number | undefined) => {
    const normalized = normalizeTimestamp(timestamp);
    if (!normalized) return "Unknown";
    return new Intl.DateTimeFormat(undefined, {
      month: "short",
      day: "numeric",
      year: "numeric",
    }).format(new Date(normalized));
  };

  const formatStatus = (value: string) =>
    value
      .split("_")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(" ");

  const getAmount = (transaction: ConnectedTransaction) =>
    transaction.amountPaid ?? transaction.amount;

  const paginationItemClassName = (isCurrentPage: boolean) =>
    `${isCurrentPage ? "button-filled" : "button-faded"} h-8 min-w-8 px-2`;

  const loadTransactions = async (args: {
    pageNumber: number;
    pageSize: number;
    productId?: string;
    orderId?: string;
  }) => {
    if (!searchRef) return;
    isLoading = true;
    error = null;
    try {
      result = (await client.action(searchRef, args)) as ConnectedTransactionList;
    } catch (cause) {
      error = cause instanceof Error
        ? cause.message
        : "Could not load billing history";
    } finally {
      isLoading = false;
    }
  };

  $effect(() => {
    void loadTransactions({
      pageNumber,
      pageSize,
      ...(productId ? { productId } : {}),
      ...(orderId ? { orderId } : {}),
    });
  });

  const transactions = $derived(result?.items ?? []);
  const pagination = $derived(result?.pagination);
</script>

{#snippet paginationItems(api: UsePaginationContext)}
  {#each api().pages as page, index (`${page.type}-${page.type === "page" ? page.value : index}`)}
    {#if page.type === "page"}
      <Pagination.Item
        type="page"
        value={page.value}
        class={paginationItemClassName(page.value === api().page)}
      >
        {page.value}
      </Pagination.Item>
    {:else}
      <Pagination.Ellipsis
        index={index}
        class="body-s px-1 text-foreground-muted"
      >
        ...
      </Pagination.Ellipsis>
    {/if}
  {/each}
{/snippet}

{#if searchRef}
  <section class={`space-y-3 ${className}`}>
    <div class="flex items-center justify-between gap-3">
      <h2 class="title-m text-foreground-default">Billing history</h2>
      {#if isLoading}
        <span class="body-s text-foreground-placeholder">Loading...</span>
      {/if}
    </div>

    {#if error}
      <div class="rounded-lg border border-red-300 bg-red-50 px-3 py-2 text-sm text-red-700">
        {error}
      </div>
    {/if}

    <div class="overflow-hidden rounded-xl border border-border-subtle">
      <div class="overflow-x-auto">
        <table class="w-full min-w-[40rem] border-collapse text-left">
          <thead class="bg-surface-subtle">
            <tr class="label-s text-foreground-muted">
              <th class="px-4 py-3 font-medium">Date</th>
              <th class="px-4 py-3 font-medium">Description</th>
              <th class="px-4 py-3 font-medium">Type</th>
              <th class="px-4 py-3 font-medium">Status</th>
              <th class="px-4 py-3 text-right font-medium">Amount</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-border-subtle bg-surface-base">
            {#if transactions.length > 0}
              {#each transactions as transaction (transaction.id)}
                <tr class="body-s text-foreground-default">
                  <td class="px-4 py-3">{formatDate(transaction.createdAt)}</td>
                  <td class="px-4 py-3">{transaction.description ?? transaction.id}</td>
                  <td class="px-4 py-3">{formatStatus(transaction.type)}</td>
                  <td class="px-4 py-3">{formatStatus(transaction.status)}</td>
                  <td class="px-4 py-3 text-right">
                    {formatPrice(getAmount(transaction), transaction.currency)}
                  </td>
                </tr>
              {/each}
            {:else}
              <tr>
                <td
                  colspan="5"
                  class="px-4 py-8 text-center body-s text-foreground-muted"
                >
                  {isLoading ? "Loading billing history..." : "No transactions yet"}
                </td>
              </tr>
            {/if}
          </tbody>
        </table>
      </div>
    </div>

    {#if pagination && pagination.totalPages > 1}
      <Pagination.Root
        count={pagination.totalRecords}
        page={pagination.currentPage}
        {pageSize}
        siblingCount={1}
        onPageChange={(details: PaginationPageChangeDetails) => {
          pageNumber = details.page;
        }}
        class={`flex items-center justify-end gap-2 ${isLoading ? "pointer-events-none opacity-60" : ""}`}
      >
        <Pagination.PrevTrigger
          class="icon-button-ghost-sm"
          aria-label="Previous page"
        >
          <ChevronLeft aria-hidden="true" class="size-4" />
        </Pagination.PrevTrigger>
        <Pagination.Context render={paginationItems} />
        <Pagination.NextTrigger
          class="icon-button-ghost-sm"
          aria-label="Next page"
        >
          <ChevronRight aria-hidden="true" class="size-4" />
        </Pagination.NextTrigger>
      </Pagination.Root>
    {/if}
  </section>
{/if}

// src/react/widgets/BillingHistory.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { useConvex } from "convex/react";
import {
  Pagination,
  type PaginationPageChangeDetails,
  type UsePaginationContext,
} from "@ark-ui/react/pagination";
import { ChevronLeft, ChevronRight } from "lucide-react";
import type {
  ConnectedBillingApi,
  ConnectedTransaction,
  ConnectedTransactionList,
} from "./types.js";
import { formatPrice } from "../shared.js";

const normalizeTimestamp = (timestamp: number | undefined): number | null => {
  if (!timestamp) return null;
  return timestamp < 1_000_000_000_000 ? timestamp * 1000 : timestamp;
};

const formatDate = (timestamp: number | undefined) => {
  const normalized = normalizeTimestamp(timestamp);
  if (!normalized) return "Unknown";
  return new Intl.DateTimeFormat(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(normalized));
};

const formatStatus = (value: string) =>
  value
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

const getAmount = (transaction: ConnectedTransaction) =>
  transaction.amountPaid ?? transaction.amount;

const paginationItemClassName = (isCurrentPage: boolean) =>
  `${isCurrentPage ? "button-filled" : "button-faded"} h-8 min-w-8 px-2`;

export const BillingHistory = ({
  api,
  pageSize = 10,
  productId,
  orderId,
  className = "",
}: {
  api: ConnectedBillingApi;
  pageSize?: number;
  productId?: string;
  orderId?: string;
  class?: string;
  className?: string;
}) => {
  const client = useConvex();
  const searchRef = api.transactions?.search;
  const [pageNumber, setPageNumber] = useState(1);
  const [result, setResult] = useState<ConnectedTransactionList | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const searchArgs = useMemo(
    () => ({
      pageNumber,
      pageSize,
      ...(productId ? { productId } : {}),
      ...(orderId ? { orderId } : {}),
    }),
    [orderId, pageNumber, pageSize, productId],
  );

  const loadTransactions = useCallback(async () => {
    if (!searchRef) return;
    setIsLoading(true);
    setError(null);
    try {
      const next = await client.action(searchRef, searchArgs);
      setResult(next as ConnectedTransactionList);
    } catch (cause) {
      setError(
        cause instanceof Error
          ? cause.message
          : "Could not load billing history",
      );
    } finally {
      setIsLoading(false);
    }
  }, [client, searchArgs, searchRef]);

  useEffect(() => {
    const timeout = setTimeout(() => {
      void loadTransactions();
    }, 0);
    return () => clearTimeout(timeout);
  }, [loadTransactions]);

  if (!searchRef) return null;

  const transactions = result?.items ?? [];
  const pagination = result?.pagination;

  return (
    <section className={`space-y-3 ${className}`}>
      <div className="flex items-center justify-between gap-3">
        <h2 className="title-m text-foreground-default">Billing history</h2>
        {isLoading && (
          <span className="body-s text-foreground-placeholder">Loading...</span>
        )}
      </div>

      {error && (
        <div className="rounded-lg border border-red-300 bg-red-50 px-3 py-2 text-sm text-red-700">
          {error}
        </div>
      )}

      <div className="overflow-hidden rounded-xl border border-border-subtle">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[40rem] border-collapse text-left">
            <thead className="bg-surface-subtle">
              <tr className="label-s text-foreground-muted">
                <th className="px-4 py-3 font-medium">Date</th>
                <th className="px-4 py-3 font-medium">Description</th>
                <th className="px-4 py-3 font-medium">Type</th>
                <th className="px-4 py-3 font-medium">Status</th>
                <th className="px-4 py-3 text-right font-medium">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border-subtle bg-surface-base">
              {transactions.length > 0 ? (
                transactions.map((transaction) => (
                  <tr
                    key={transaction.id}
                    className="body-s text-foreground-default"
                  >
                    <td className="px-4 py-3">
                      {formatDate(transaction.createdAt)}
                    </td>
                    <td className="px-4 py-3">
                      {transaction.description ?? transaction.id}
                    </td>
                    <td className="px-4 py-3">
                      {formatStatus(transaction.type)}
                    </td>
                    <td className="px-4 py-3">
                      {formatStatus(transaction.status)}
                    </td>
                    <td className="px-4 py-3 text-right">
                      {formatPrice(
                        getAmount(transaction),
                        transaction.currency,
                      )}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td
                    colSpan={5}
                    className="px-4 py-8 text-center body-s text-foreground-muted"
                  >
                    {isLoading
                      ? "Loading billing history..."
                      : "No transactions yet"}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {pagination && pagination.totalPages > 1 && (
        <Pagination.Root
          count={pagination.totalRecords}
          page={pagination.currentPage}
          pageSize={pageSize}
          siblingCount={1}
          onPageChange={(details: PaginationPageChangeDetails) =>
            setPageNumber(details.page)
          }
          className={`flex items-center justify-end gap-2 ${isLoading ? "pointer-events-none opacity-60" : ""}`}
        >
          <Pagination.PrevTrigger
            className="icon-button-ghost-sm"
            aria-label="Previous page"
          >
            <ChevronLeft aria-hidden="true" className="size-4" />
          </Pagination.PrevTrigger>
          <Pagination.Context>
            {(api: UsePaginationContext) =>
              api.pages.map(
                (page: UsePaginationContext["pages"][number], index: number) =>
                  page.type === "page" ? (
                    <Pagination.Item
                      key={page.value}
                      type="page"
                      value={page.value}
                      className={paginationItemClassName(
                        page.value === api.page,
                      )}
                    >
                      {page.value}
                    </Pagination.Item>
                  ) : (
                    <Pagination.Ellipsis
                      key={`ellipsis-${index}`}
                      index={index}
                      className="body-s px-1 text-foreground-muted"
                    >
                      ...
                    </Pagination.Ellipsis>
                  ),
              )
            }
          </Pagination.Context>
          <Pagination.NextTrigger
            className="icon-button-ghost-sm"
            aria-label="Next page"
          >
            <ChevronRight aria-hidden="true" className="size-4" />
          </Pagination.NextTrigger>
        </Pagination.Root>
      )}
    </section>
  );
};
